server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Limit connections for Clever Cloud free plan (max 5)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Add dialect explicitly
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


rapidapi.key=${RAPIDAPI_KEY}
rapidapi.host=${RAPIDAPI_HOST}
rapidapi.base-url=${RAPIDAPI_BASE_URL}

app.base-url=${APP_BASE_URL}
admin.secret=${ADMIN_SECRET}
